// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetGatewayConfig():Promise<main.GatewayConfig>;

export function Initialize():Promise<void>;

export function KeychainDelete(arg1:string,arg2:string):Promise<void>;

export function KeychainGet(arg1:string,arg2:string):Promise<string>;

export function KeychainSet(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenFileDialog():Promise<string>;

export function OpenFolderDialog():Promise<string>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function Shutdown():Promise<void>;
