// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGatewayConfig() {
  return window['go']['main']['App']['GetGatewayConfig']();
}

export function Initialize() {
  return window['go']['main']['App']['Initialize']();
}

export function KeychainDelete(arg1, arg2) {
  return window['go']['main']['App']['KeychainDelete'](arg1, arg2);
}

export function KeychainGet(arg1, arg2) {
  return window['go']['main']['App']['KeychainGet'](arg1, arg2);
}

export function KeychainSet(arg1, arg2, arg3) {
  return window['go']['main']['App']['KeychainSet'](arg1, arg2, arg3);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}
