"""add pr labels

Revision ID: 0bf172ecdc5e
Revises: 311297f80828
Create Date: 2026-06-22 01:21:41.409248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bf172ecdc5e'
down_revision: Union[str, Sequence[str], None] = '311297f80828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pr_label_definitions',
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'name', name='uq_pr_label_name')
    )
    with op.batch_alter_table('pr_label_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pr_label_definitions_id'), ['id'], unique=False)

    op.create_table('pr_labels',
    sa.Column('pull_request_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['pr_label_definitions.id'], ),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ),
    sa.PrimaryKeyConstraint('pull_request_id', 'label_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pr_labels')
    with op.batch_alter_table('pr_label_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pr_label_definitions_id'))

    op.drop_table('pr_label_definitions')
    # ### end Alembic commands ###
