"""add is_draft to pull_requests

Revision ID: 311297f80828
Revises: 25f5316ce94a
Create Date: 2026-06-22 01:17:24.390301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '311297f80828'
down_revision: Union[str, Sequence[str], None] = '25f5316ce94a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pull_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_draft', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pull_requests', schema=None) as batch_op:
        batch_op.drop_column('is_draft')

    # ### end Alembic commands ###
