"""initial_uuid_schema

Revision ID: a58c8a7aeb0a
Revises: 4a5b6c7d8e9f
Create Date: 2026-07-15 21:38:55.079463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a58c8a7aeb0a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('build_status',
    sa.Column('repo_id', sa.Uuid(), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('commit_message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('triggered_by', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('details_url', sa.String(length=512), nullable=True),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('build_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_build_status_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_build_status_repo_id'), ['repo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_build_status_status'), ['status'], unique=False)

    op.create_table('repositories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('default_branch', sa.String(length=50), nullable=True),
    sa.Column('forked_from_id', sa.Uuid(), nullable=True),
    sa.Column('fork_count', sa.Integer(), nullable=True),
    sa.Column('star_count', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['forked_from_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repositories_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_repositories_name'), ['name'], unique=False)

    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('activities',
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_id'), ['id'], unique=False)

    op.create_table('branches',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('is_protected', sa.Boolean(), nullable=True),
    sa.Column('require_code_review', sa.Boolean(), nullable=True),
    sa.Column('require_status_checks', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_branches_id'), ['id'], unique=False)

    op.create_table('issues',
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('issue_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('assignee_id', sa.Uuid(), nullable=True),
    sa.Column('closed_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issues_id'), ['id'], unique=False)

    op.create_table('labels',
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_labels_id'), ['id'], unique=False)

    op.create_table('notification_preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email_on_mention', sa.Boolean(), nullable=False),
    sa.Column('email_on_pr_review', sa.Boolean(), nullable=False),
    sa.Column('email_on_issue_comment', sa.Boolean(), nullable=False),
    sa.Column('email_on_pr_merge', sa.Boolean(), nullable=False),
    sa.Column('email_on_release', sa.Boolean(), nullable=False),
    sa.Column('in_app_on_mention', sa.Boolean(), nullable=False),
    sa.Column('in_app_on_pr_review', sa.Boolean(), nullable=False),
    sa.Column('in_app_on_issue_comment', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_preferences_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_preferences_user_id'), ['user_id'], unique=True)

    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_repository_id'), ['repository_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_notifications_user_id_is_read', ['user_id', 'is_read'], unique=False)

    op.create_table('pr_label_definitions',
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'name', name='uq_pr_label_name')
    )
    with op.batch_alter_table('pr_label_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pr_label_definitions_id'), ['id'], unique=False)

    op.create_table('pull_requests',
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_branch', sa.String(length=100), nullable=False),
    sa.Column('target_branch', sa.String(length=100), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=True),
    sa.Column('merged_by', sa.Uuid(), nullable=True),
    sa.Column('merged_commit_hash', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['merged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pull_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pull_requests_id'), ['id'], unique=False)

    op.create_table('realtime_rooms',
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('realtime_rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_realtime_rooms_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_realtime_rooms_repository_id'), ['repository_id'], unique=True)

    op.create_table('releases',
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('release_number', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('commit_hash', sa.String(length=40), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=True),
    sa.Column('is_prerelease', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_releases_id'), ['id'], unique=False)

    op.create_table('repo_label_definitions',
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'name', name='uq_repo_label_name')
    )
    with op.batch_alter_table('repo_label_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repo_label_definitions_id'), ['id'], unique=False)

    op.create_table('repository_members',
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repository_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repository_members_id'), ['id'], unique=False)

    op.create_table('ssh_keys',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('fingerprint', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ssh_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ssh_keys_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_ssh_keys_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ssh_keys_user_id'), ['user_id'], unique=False)

    op.create_table('stargazers',
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'user_id', name='uq_repo_user_star')
    )
    with op.batch_alter_table('stargazers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stargazers_id'), ['id'], unique=False)

    op.create_table('user_oauth_accounts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('provider_username', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.String(length=512), nullable=True),
    sa.Column('refresh_token', sa.String(length=256), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_user_oauth_provider')
    )
    with op.batch_alter_table('user_oauth_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_oauth_accounts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_oauth_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('webhooks',
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('events', sa.Text(), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('last_response_status', sa.Integer(), nullable=True),
    sa.Column('last_response_body', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhooks_id'), ['id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('reply_to_id', sa.Uuid(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['reply_to_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['realtime_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_id'), ['id'], unique=False)
        batch_op.create_index('ix_chat_messages_room_created', ['room_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_room_id'), ['room_id'], unique=False)

    op.create_table('commits',
    sa.Column('hash', sa.String(length=40), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('author_name', sa.String(length=100), nullable=False),
    sa.Column('author_email', sa.String(length=100), nullable=False),
    sa.Column('committer_name', sa.String(length=100), nullable=False),
    sa.Column('committer_email', sa.String(length=100), nullable=False),
    sa.Column('commit_message', sa.Text(), nullable=False),
    sa.Column('commit_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('parent_hashes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    with op.batch_alter_table('commits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commits_id'), ['id'], unique=False)

    op.create_table('issue_comments',
    sa.Column('issue_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issue_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issue_comments_id'), ['id'], unique=False)

    op.create_table('issue_labels',
    sa.Column('issue_id', sa.Uuid(), nullable=True),
    sa.Column('label_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], )
    )
    op.create_table('pr_activities',
    sa.Column('pull_request_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pr_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pr_activities_id'), ['id'], unique=False)

    op.create_table('pr_comments',
    sa.Column('pull_request_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('commit_hash', sa.String(length=40), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['pr_comments.id'], ),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pr_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pr_comments_id'), ['id'], unique=False)

    op.create_table('pr_labels',
    sa.Column('pull_request_id', sa.Uuid(), nullable=False),
    sa.Column('label_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['pr_label_definitions.id'], ),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ),
    sa.PrimaryKeyConstraint('pull_request_id', 'label_id')
    )
    op.create_table('pr_reviews',
    sa.Column('pull_request_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pr_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pr_reviews_id'), ['id'], unique=False)

    op.create_table('release_assets',
    sa.Column('release_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('release_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_release_assets_id'), ['id'], unique=False)

    op.create_table('repo_labels',
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('label_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['repo_label_definitions.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('repository_id', 'label_id')
    )
    op.create_table('room_members',
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_muted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['realtime_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'user_id', name='uq_room_member')
    )
    with op.batch_alter_table('room_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_members_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_members_room_id'), ['room_id'], unique=False)

    op.create_table('webhook_deliveries',
    sa.Column('webhook_id', sa.Uuid(), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('request_headers', sa.Text(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('response_headers', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_id'))

    op.drop_table('webhook_deliveries')
    with op.batch_alter_table('room_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_members_room_id'))
        batch_op.drop_index(batch_op.f('ix_room_members_id'))

    op.drop_table('room_members')
    op.drop_table('repo_labels')
    with op.batch_alter_table('release_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_release_assets_id'))

    op.drop_table('release_assets')
    with op.batch_alter_table('pr_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pr_reviews_id'))

    op.drop_table('pr_reviews')
    op.drop_table('pr_labels')
    with op.batch_alter_table('pr_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pr_comments_id'))

    op.drop_table('pr_comments')
    with op.batch_alter_table('pr_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pr_activities_id'))

    op.drop_table('pr_activities')
    op.drop_table('issue_labels')
    with op.batch_alter_table('issue_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_comments_id'))

    op.drop_table('issue_comments')
    with op.batch_alter_table('commits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commits_id'))

    op.drop_table('commits')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_room_id'))
        batch_op.drop_index('ix_chat_messages_room_created')
        batch_op.drop_index(batch_op.f('ix_chat_messages_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhooks_id'))

    op.drop_table('webhooks')
    with op.batch_alter_table('user_oauth_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_oauth_accounts_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_oauth_accounts_id'))

    op.drop_table('user_oauth_accounts')
    with op.batch_alter_table('stargazers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stargazers_id'))

    op.drop_table('stargazers')
    with op.batch_alter_table('ssh_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ssh_keys_user_id'))
        batch_op.drop_index(batch_op.f('ix_ssh_keys_id'))
        batch_op.drop_index(batch_op.f('ix_ssh_keys_fingerprint'))

    op.drop_table('ssh_keys')
    with op.batch_alter_table('repository_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repository_members_id'))

    op.drop_table('repository_members')
    with op.batch_alter_table('repo_label_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repo_label_definitions_id'))

    op.drop_table('repo_label_definitions')
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_releases_id'))

    op.drop_table('releases')
    with op.batch_alter_table('realtime_rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_realtime_rooms_repository_id'))
        batch_op.drop_index(batch_op.f('ix_realtime_rooms_id'))

    op.drop_table('realtime_rooms')
    with op.batch_alter_table('pull_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pull_requests_id'))

    op.drop_table('pull_requests')
    with op.batch_alter_table('pr_label_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pr_label_definitions_id'))

    op.drop_table('pr_label_definitions')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_id_is_read')
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_repository_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_id'))
        batch_op.drop_index('ix_notifications_created_at')

    op.drop_table('notifications')
    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_preferences_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_preferences_id'))

    op.drop_table('notification_preferences')
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_labels_id'))

    op.drop_table('labels')
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issues_id'))

    op.drop_table('issues')
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branches_id'))

    op.drop_table('branches')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_id'))

    op.drop_table('activities')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repositories_name'))
        batch_op.drop_index(batch_op.f('ix_repositories_id'))

    op.drop_table('repositories')
    with op.batch_alter_table('build_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_build_status_status'))
        batch_op.drop_index(batch_op.f('ix_build_status_repo_id'))
        batch_op.drop_index(batch_op.f('ix_build_status_id'))

    op.drop_table('build_status')
    # ### end Alembic commands ###
