"""add star_count and stargazers table

Revision ID: c75cd32eb873
Revises: 71b8169a1172
Create Date: 2026-06-22 00:07:45.948737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c75cd32eb873'
down_revision: Union[str, Sequence[str], None] = '42017859e904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stargazers',
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'user_id', name='uq_repo_user_star')
    )
    with op.batch_alter_table('stargazers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stargazers_id'), ['id'], unique=False)

    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('star_count', sa.Integer(), nullable=False, server_default=sa.text('0')))

    with op.batch_alter_table('ssh_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ssh_keys_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ssh_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ssh_keys_id'))

    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.drop_column('star_count')

    with op.batch_alter_table('stargazers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stargazers_id'))

    op.drop_table('stargazers')
    # ### end Alembic commands ###
