import type { ThemeConfig } from 'antd';

export const perseusTheme: ThemeConfig = {
  token: {
    colorPrimary: '#1f6feb',
    colorInfo: '#58a6ff',
    colorSuccess: '#3fb950',
    colorWarning: '#d29922',
    colorError: '#f85149',
    colorTextBase: '#e6edf3',
    colorBgBase: '#0d1117',
    colorBgContainer: '#161b22',
    colorBgElevated: '#1c2128',
    colorBgLayout: '#0d1117',
    colorBorder: '#30363d',
    colorBorderSecondary: '#21262d',
    colorText: '#e6edf3',
    colorTextSecondary: '#8b949e',
    colorTextTertiary: '#6e7681',
    borderRadius: 8,
    fontFamily: "'Inter', system-ui, sans-serif",
    fontSize: 14,
    controlHeight: 36,
    wireframe: false,
  },
  components: {
    Layout: {
      headerBg: '#161b22',
      bodyBg: '#0d1117',
      siderBg: '#010409',
      triggerBg: '#161b22',
      headerHeight: 48,
    },
    Menu: {
      itemBg: 'transparent',
      itemColor: '#8b949e',
      itemHoverColor: '#e6edf3',
      itemHoverBg: '#1c2333',
      itemSelectedColor: '#e6edf3',
      itemSelectedBg: '#1a2332',
      itemActiveBg: '#1a2332',
      subMenuItemBg: 'transparent',
      popupBg: '#161b22',
      iconSize: 20,
      itemHeight: 40,
      itemBorderRadius: 8,
    },
    Button: {
      primaryShadow: 'none',
      defaultBg: '#21262d',
      defaultColor: '#e6edf3',
      defaultBorderColor: '#30363d',
      defaultHoverBg: '#30363d',
      defaultHoverBorderColor: '#8b949e',
      textHoverBg: '#1c2333',
    },
    Card: {
      colorBgContainer: '#161b22',
      colorBorderSecondary: '#21262d',
      paddingLG: 24,
    },
    Modal: {
      contentBg: '#161b22',
      headerBg: '#161b22',
      footerBg: '#161b22',
      titleColor: '#e6edf3',
      borderRadiusLG: 12,
    },
    Input: {
      colorBgContainer: '#0d1117',
      colorBorder: '#30363d',
      activeBorderColor: '#1f6feb',
      hoverBorderColor: '#58a6ff',
      colorText: '#e6edf3',
      colorTextPlaceholder: '#6e7681',
      addonBg: '#161b22',
    },
    Select: {
      colorBgContainer: '#0d1117',
      colorBorder: '#30363d',
      colorText: '#e6edf3',
      optionSelectedBg: '#1a2332',
      optionActiveBg: '#1c2333',
    },
    Table: {
      colorBgContainer: 'transparent',
      borderColor: '#21262d',
      headerColor: '#8b949e',
      headerBg: 'transparent',
      rowHoverBg: '#1c2333',
    },
    Tabs: {
      colorBgContainer: 'transparent',
      inkBarColor: '#1f6feb',
      itemColor: '#8b949e',
      itemSelectedColor: '#e6edf3',
      itemHoverColor: '#e6edf3',
    },
    Tag: {
      defaultBg: '#1c2128',
      defaultColor: '#8b949e',
    },
    Badge: {
      colorBgContainer: '#1f6feb',
    },
    Breadcrumb: {
      itemColor: '#8b949e',
      lastItemColor: '#e6edf3',
      separatorColor: '#30363d',
    },
    Tooltip: {
      colorBgSpotlight: '#1c2128',
    },
    Divider: {
      colorBorder: '#21262d',
    },
    Dropdown: {
      colorBgElevated: '#161b22',
      colorBorder: '#30363d',
      controlItemBgHover: '#1c2333',
    },
    List: {
      colorBgContainer: 'transparent',
    },
    Tree: {
      colorBgContainer: 'transparent',
      nodeHoverBg: '#1c2333',
      nodeSelectedBg: '#1a2332',
      colorText: '#e6edf3',
    },
  },
};
